CREATE TABLE `lab1demo`.`student` ( `kdno` INT NULL DEFAULT NULL,
`kcno` INT NULL DEFAULT NULL ,
`ccno` INT NULL DEFAULT NULL ,
`kdname` VARCHAR(50) NULL DEFAULT NULL ,
`exptime`  VARCHAR(50) NULL DEFAULT NULL,
`seat` VARCHAR(50) NULL DEFAULT NULL ) ENGINE = InnoDB