CREATE TABLE `lab1demo`.`room`
( `kdno` INT NULL DEFAULT NULL,
`kcno` INT NULL DEFAULT NULL ,
`ccno` INT NULL DEFAULT NULL ,
`kdname` VARCHAR(50) NULL DEFAULT NULL ,
`exptime`  VARCHAR(50) NULL DEFAULT NULL,
`papername` VARCHAR(50) NULL DEFAULT NULL ) ENGINE = InnoDB