CREATE TABLE `lab1demo`.`student` ( `registno` VARCHAR(50) NULL DEFAULT NULL ,
`name` VARCHAR(50) NULL DEFAULT NULL ,
`kdno` INT NULL DEFAULT NULL ,
`kcno` INT NULL DEFAULT NULL ,
`ccno` INT NULL DEFAULT NULL ,
`seat` INT NULL DEFAULT NULL ) ENGINE = InnoDB
